import Head from "next/head";
import { Amplify } from "aws-amplify";
import awsconfig from "../aws-exports";
import { Provider } from "react-redux";
import store from "../utils/fileStore";

import HomeSection from "../components/HomeSection";
Amplify.configure(awsconfig);

export default function Home() {
  return (
    <>
      <Head>
        <title>My Elephant App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <HomeSection />
      </Provider>
    </>
  );
}
