import Head from "next/head";
import "@aws-amplify/ui-react/styles.css";
import HomeSection from "../components/HomeSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection />
    </>
  );
}
